AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Template para criar uma infraestrutura AWS com VPC, ALB, EC2 com Auto Scaling, S3 e DynamoDB para uma aplicacao Python.

Parameters:
  AppS3File:
    Description: "Nome do arquivo Python da aplicação dentro do Bucket S3"
    Type: String
    Default: "app.py"
  InstanceType:
    Description: "Tipo de instância EC2 para o Auto Scaling Group"
    Type: String
    Default: "t2.micro"
  AMI:
    Description: "AMI a ser usada para as instâncias EC2"
    Type: String
    Default: "ami-07caf09b362be10b8"
  BucketName:
    Description: "Nome do bucket S3 que contém a aplicacao Python"
    Type: String
    Default: "bucket-projeto-lucam"

Resources:
  # Role IAM para acesso ao S3 e DynamoDB 
  S3DynamoDBAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "AccessS3BucketAndDynamoDB"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:GetObject"
                Resource: !Sub "arn:aws:s3:::${BucketName}/*"
              - Effect: "Allow"
                Action:
                  - "dynamodb:Scan"
                  - "dynamodb:PutItem"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:UpdateItem"
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Users_luca"

  # Instance Profile
  S3DynamoDBInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref S3DynamoDBAccessRole

  # VPC Configuration
  MinhaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MinhaVPC

  # Internet Gateway Configuration
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MeuInternetGateway

  # Attach Internet Gateway to VPC
  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MinhaVPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnet 1
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MinhaVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: PublicSubnet1

  # Subnet pública 2
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MinhaVPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: PublicSubnet2

  # Criar tabela de rota pública
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MinhaVPC

  # Criar rota para a internet
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Associar a rota da subnet 1 com a tabela de rota pública
  PublicSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  # Associar a rota da subnet 2 com a tabela de rota pública
  PublicSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Security Group para as instâncias EC2 com especificação de regras de entrada para o tráfego HTTP na porta 80 e SSH na porta 22
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for web instances"
      VpcId: !Ref MinhaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  # Security Group para o ALB com especificação de regras de entrada para o tráfego HTTP na porta 80
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for ALB"
      VpcId: !Ref MinhaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # Load Balancer para distribuir o tráfego entre as instâncias EC2
  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Type: "application"

  # Listener para o ALB 
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref MyALB
      Port: 80
      Protocol: "HTTP"

  # Elastic Load Balancer para distribuir o tráfego entre as instâncias EC2 saudáveis
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref MinhaVPC
      Port: 80
      Protocol: "HTTP"
      HealthCheckPath: "/"
      HealthCheckProtocol: "HTTP"
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2

  # Launch Configuration para as instâncias EC2 do Auto Scaling Group
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      IamInstanceProfile: !Ref S3DynamoDBInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum install -y python3-pip python3

          # Instalar o Flask
          sudo pip3 install flask

          # Instalar AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

          # Instalar AWS SDK para Python (Boto3)
          sudo pip3 install boto3

          # Criar diretório para a aplicação
          mkdir -p /home/ubuntu/app
          cd /home/ubuntu/app

          # Baixar a aplicação do S3
          aws s3 cp s3://${BucketName}/${AppS3File} /home/ubuntu/app/app.py

          # Executar a aplicação
          python3 /home/ubuntu/app/app.py

  # Auto Scaling Group para escalabilidade da aplicação
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref LaunchConfig
      MinSize: "1"
      MaxSize: "5"
      DesiredCapacity: "3"
      TargetGroupARNs:
        - !Ref MyTargetGroup
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
    # Tags para a identificação do Auto Scaling Group
    Tags:
      - Key: Name
        Value: "ASG Luca"
        PropagateAtLaunch: true

  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: "SimpleScaling"
      ScalingAdjustment: 1
      AdjustmentType: "ChangeInCapacity"
      Cooldown: 120

  ScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: "SimpleScaling"
      ScalingAdjustment: -1
      AdjustmentType: "ChangeInCapacity"
      Cooldown: 120

  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm para CPU > 70%"
      Namespace: "AWS/EC2"
      MetricName: "CPUUtilization"
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value: !Ref AutoScalingGroup
      Statistic: "Average"
      Period: 30
      EvaluationPeriods: 2
      Threshold: 1 
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !Ref ScaleUpPolicy
      
  CPUAlarmLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm para CPU < 30%"
      Namespace: "AWS/EC2"
      MetricName: "CPUUtilization"
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value: !Ref AutoScalingGroup
      Statistic: "Average"
      Period: 300
      EvaluationPeriods: 2
      Threshold: 0.5
      ComparisonOperator: "LessThanThreshold"
      AlarmActions:
        - !Ref ScaleDownPolicy

  # Alarmes utilizando número de requisições ao invés de uso de CPU
  # HighRequestCountAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmDescription: "Alarm when request count is high"
  #     Namespace: "AWS/ApplicationELB"
  #     MetricName: "RequestCountPerTarget"
  #     Dimensions:
  #       - Name: "TargetGroup"
  #         Value: !Ref TargetGroupARN
  #     Statistic: "Sum"
  #     Period: 30
  #     EvaluationPeriods: 2
  #     Threshold: 100
  #     ComparisonOperator: "GreaterThanThreshold"
  #     AlarmActions:
  #       - !Ref ScaleUpPolicy

  # LowRequestCountAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmDescription: "Alarm when request count is low"
  #     Namespace: "AWS/ApplicationELB"
  #     MetricName: "RequestCountPerTarget"
  #     Dimensions:
  #       - Name: "TargetGroup"
  #         Value: !Ref TargetGroupARN
  #     Statistic: "Sum"
  #     Period: 30
  #     EvaluationPeriods: 3
  #     Threshold: 10
  #     ComparisonOperator: "LessThanThreshold"
  #     AlarmActions:
  #       - !Ref ScaleDownPolicy

  # Tabela DynamoDB para armazenar os usuários
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Users_luca"
      AttributeDefinitions:
        - AttributeName: "UserID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "UserID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: "Name"
          Value: "Users_luca"

  # Endpoint VPC para o DynamoDB para acesso privado
  DynamoDBVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref MinhaVPC
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.dynamodb"
      VpcEndpointType: "Interface"
      SubnetIds:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      PrivateDnsEnabled: false
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "dynamodb:*"
            Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Users_luca"

# Output do DNS do Load Balancer para acesso à aplicação
Outputs:
  LoadBalancerDNSName:
    Description: "DNS do Load Balancer"
    Value: !GetAtt MyALB.DNSName